version: '3.8'

services:
  database:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
    env_file:
      - .env
    ports:
      - "5455:5432"
    expose:
      - 5432